<?php

declare(strict_types=1);

namespace App\Enums;

/*
* The number here represents the national dex number of the Pokemon.
*/
enum Gen1Pokemon: int
{
    case BULBASAUR = 1;
    case IVYSAUR = 2;
    case VENUSAUR = 3;
    case CHARMANDER = 4;
    case CHARMELEON = 5;
    case CHARIZARD = 6;
    case SQUIRTLE = 7;
    case WARTORTLE = 8;
    case BLASTOISE = 9;
    case CATERPIE = 10;
    case METAPOD = 11;
    case BUTTERFREE = 12;
    case WEEDLE = 13;
    case KAKUNA = 14;
    case BEEDRILL = 15;
    case PIDGEY = 16;
    case PIDGEOTTO = 17;
    case PIDGEOT = 18;
    case RATTATA = 19;
    case RATICATE = 20;
    case SPEAROW = 21;
    case FEAROW = 22;
    case EKANS = 23;
    case ARBOK = 24;
    case PIKACHU = 25;
    case RAICHU = 26;
    case SANDSHREW = 27;
    case SANDSLASH = 28;
    case NIDORAN_FEMALE = 29;
    case NIDORINA = 30;
    case NIDOQUEEN = 31;
    case NIDORAN_MALE = 32;
    case NIDORINO = 33;
    case NIDOKING = 34;
    case CLEFAIRY = 35;
    case CLEFABLE = 36;
    case VULPIX = 37;
    case NINETALES = 38;
    case JIGGLYPUFF = 39;
    case WIGGLYTUFF = 40;
    case ZUBAT = 41;
    case GOLBAT = 42;
    case ODDISH = 43;
    case GLOOM = 44;
    case VILEPLUME = 45;
    case PARAS = 46;
    case PARASECT = 47;
    case VENONAT = 48;
    case VENOMOTH = 49;
    case DIGLETT = 50;
    case DUGTRIO = 51;
    case MEOWTH = 52;
    case PERSIAN = 53;
    case PSYDUCK = 54;
    case GOLDUCK = 55;
    case MANKEY = 56;
    case PRIMEAPE = 57;
    case GROWLITHE = 58;
    case ARCANINE = 59;
    case POLIWAG = 60;
    case POLIWHIRL = 61;
    case POLIWRATH = 62;
    case ABRA = 63;
    case KADABRA = 64;
    case ALAKAZAM = 65;
    case MACHOP = 66;
    case MACHOKE = 67;
    case MACHAMP = 68;
    case BELLSPROUT = 69;
    case WEEPINBELL = 70;
    case VICTREEBEL = 71;
    case TENTACOOL = 72;
    case TENTACRUEL = 73;
    case GEODUDE = 74;
    case GRAVELER = 75;
    case GOLEM = 76;
    case PONYTA = 77;
    case RAPIDASH = 78;
    case SLOWPOKE = 79;
    case SLOWBRO = 80;
    case MAGNEMITE = 81;
    case MAGNETON = 82;
    case FARFETCHD = 83;
    case DODUO = 84;
    case DODRIO = 85;
    case SEEL = 86;
    case DEWGONG = 87;
    case GRIMER = 88;
    case MUK = 89;
    case SHELLDER = 90;
    case CLOYSTER = 91;
    case GASTLY = 92;
    case HAUNTER = 93;
    case GENGAR = 94;
    case ONIX = 95;
    case DROWZEE = 96;
    case HYPNO = 97;
    case KRABBY = 98;
    case KINGLER = 99;
    case VOLTORB = 100;
    case ELECTRODE = 101;
    case EXEGGCUTE = 102;
    case EXEGGUTOR = 103;
    case CUBONE = 104;
    case MAROWAK = 105;
    case HITMONLEE = 106;
    case HITMONCHAN = 107;
    case LICKITUNG = 108;
    case KOFFING = 109;
    case WEEZING = 110;
    case RHYHORN = 111;
    case RHYDON = 112;
    case CHANSEY = 113;
    case TANGELA = 114;
    case KANGASKHAN = 115;
    case HORSEA = 116;
    case SEADRA = 117;
    case GOLDEEN = 118;
    case SEAKING = 119;
    case STARYU = 120;
    case STARMIE = 121;
    case MR_MIME = 122;
    case SCYTHER = 123;
    case JYNX = 124;
    case ELECTABUZZ = 125;
    case MAGMAR = 126;
    case PINSIR = 127;
    case TAUROS = 128;
    case MAGIKARP = 129;
    case GYARADOS = 130;
    case LAPRAS = 131;
    case DITTO = 132;
    case EEVEE = 133;
    case VAPOREON = 134;
    case JOLTEON = 135;
    case FLAREON = 136;
    case PORYGON = 137;
    case OMANYTE = 138;
    case OMASTAR = 139;
    case KABUTO = 140;
    case KABUTOPS = 141;
    case AERODACTYL = 142;
    case SNORLAX = 143;
    case ARTICUNO = 144;
    case ZAPDOS = 145;
    case MOLTRES = 146;
    case DRATINI = 147;
    case DRAGONAIR = 148;
    case DRAGONITE = 149;
    case MEWTWO = 150;
    case MEW = 151;

    public function name(): string
    {
        return match ($this) {
            self::BULBASAUR => 'Bulbasaur',
            self::IVYSAUR => 'Ivysaur',
            self::VENUSAUR => 'Venusaur',
            self::CHARMANDER => 'Charmander',
            self::CHARMELEON => 'Charmeleon',
            self::CHARIZARD => 'Charizard',
            self::SQUIRTLE => 'Squirtle',
            self::WARTORTLE => 'Wartortle',
            self::BLASTOISE => 'Blastoise',
            self::CATERPIE => 'Caterpie',
            self::METAPOD => 'Metapod',
            self::BUTTERFREE => 'Butterfree',
            self::WEEDLE => 'Weedle',
            self::KAKUNA => 'Kakuna',
            self::BEEDRILL => 'Beedrill',
            self::PIDGEY => 'Pidgey',
            self::PIDGEOTTO => 'Pidgeotto',
            self::PIDGEOT => 'Pidgeot',
            self::RATTATA => 'Rattata',
            self::RATICATE => 'Raticate',
            self::SPEAROW => 'Spearow',
            self::FEAROW => 'Fearow',
            self::EKANS => 'Ekans',
            self::ARBOK => 'Arbok',
            self::PIKACHU => 'Pikachu',
            self::RAICHU => 'Raichu',
            self::SANDSHREW => 'Sandshrew',
            self::SANDSLASH => 'Sandslash',
            self::NIDORAN_FEMALE => 'Nidoran♀',
            self::NIDORINA => 'Nidorina',
            self::NIDOQUEEN => 'Nidoqueen',
            self::NIDORAN_MALE => 'Nidoran♂',
            self::NIDORINO => 'Nidorino',
            self::NIDOKING => 'Nidoking',
            self::CLEFAIRY => 'Clefairy',
            self::CLEFABLE => 'Clefable',
            self::VULPIX => 'Vulpix',
            self::NINETALES => 'Ninetales',
            self::JIGGLYPUFF => 'Jigglypuff',
            self::WIGGLYTUFF => 'Wigglytuff',
            self::ZUBAT => 'Zubat',
            self::GOLBAT => 'Golbat',
            self::ODDISH => 'Oddish',
            self::GLOOM => 'Gloom',
            self::VILEPLUME => 'Vileplume',
            self::PARAS => 'Paras',
            self::PARASECT => 'Parasect',
            self::VENONAT => 'Venonat',
            self::VENOMOTH => 'Venomoth',
            self::DIGLETT => 'Diglett',
            self::DUGTRIO => 'Dugtrio',
            self::MEOWTH => 'Meowth',
            self::PERSIAN => 'Persian',
            self::PSYDUCK => 'Psyduck',
            self::GOLDUCK => 'Golduck',
            self::MANKEY => 'Mankey',
            self::PRIMEAPE => 'Primeape',
            self::GROWLITHE => 'Growlithe',
            self::ARCANINE => 'Arcanine',
            self::POLIWAG => 'Poliwag',
            self::POLIWHIRL => 'Poliwhirl',
            self::POLIWRATH => 'Poliwrath',
            self::ABRA => 'Abra',
            self::KADABRA => 'Kadabra',
            self::ALAKAZAM => 'Alakazam',
            self::MACHOP => 'Machop',
            self::MACHOKE => 'Machoke',
            self::MACHAMP => 'Machamp',
            self::BELLSPROUT => 'Bellsprout',
            self::WEEPINBELL => 'Weepinbell',
            self::VICTREEBEL => 'Victreebel',
            self::TENTACOOL => 'Tentacool',
            self::TENTACRUEL => 'Tentacruel',
            self::GEODUDE => 'Geodude',
            self::GRAVELER => 'Graveler',
            self::GOLEM => 'Golem',
            self::PONYTA => 'Ponyta',
            self::RAPIDASH => 'Rapidash',
            self::SLOWPOKE => 'Slowpoke',
            self::SLOWBRO => 'Slowbro',
            self::MAGNEMITE => 'Magnemite',
            self::MAGNETON => 'Magneton',
            self::FARFETCHD => 'Farfetch\'d',
            self::DODUO => 'Doduo',
            self::DODRIO => 'Dodrio',
            self::SEEL => 'Seel',
            self::DEWGONG => 'Dewgong',
            self::GRIMER => 'Grimer',
            self::MUK => 'Muk',
            self::SHELLDER => 'Shellder',
            self::CLOYSTER => 'Cloyster',
            self::GASTLY => 'Gastly',
            self::HAUNTER => 'Haunter',
            self::GENGAR => 'Gengar',
            self::ONIX => 'Onix',
            self::DROWZEE => 'Drowzee',
            self::HYPNO => 'Hypno',
            self::KRABBY => 'Krabby',
            self::KINGLER => 'Kingler',
            self::VOLTORB => 'Voltorb',
            self::ELECTRODE => 'Electrode',
            self::EXEGGCUTE => 'Exeggcute',
            self::EXEGGUTOR => 'Exeggutor',
            self::CUBONE => 'Cubone',
            self::MAROWAK => 'Marowak',
            self::HITMONLEE => 'Hitmonlee',
            self::HITMONCHAN => 'Hitmonchan',
            self::LICKITUNG => 'Lickitung',
            self::KOFFING => 'Koffing',
            self::WEEZING => 'Weezing',
            self::RHYHORN => 'Rhyhorn',
            self::RHYDON => 'Rhydon',
            self::CHANSEY => 'Chansey',
            self::TANGELA => 'Tangela',
            self::KANGASKHAN => 'Kangaskhan',
            self::HORSEA => 'Horsea',
            self::SEADRA => 'Seadra',
            self::GOLDEEN => 'Goldeen',
            self::SEAKING => 'Seaking',
            self::STARYU => 'Staryu',
            self::STARMIE => 'Starmie',
            self::MR_MIME => 'Mr. Mime',
            self::SCYTHER => 'Scyther',
            self::JYNX => 'Jynx',
            self::ELECTABUZZ => 'Electabuzz',
            self::MAGMAR => 'Magmar',
            self::PINSIR => 'Pinsir',
            self::TAUROS => 'Tauros',
            self::MAGIKARP => 'Magikarp',
            self::GYARADOS => 'Gyarados',
            self::LAPRAS => 'Lapras',
            self::DITTO => 'Ditto',
            self::EEVEE => 'Eevee',
            self::VAPOREON => 'Vaporeon',
            self::JOLTEON => 'Jolteon',
            self::FLAREON => 'Flareon',
            self::PORYGON => 'Porygon',
            self::OMANYTE => 'Omanyte',
            self::OMASTAR => 'Omastar',
            self::KABUTO => 'Kabuto',
            self::KABUTOPS => 'Kabutops',
            self::AERODACTYL => 'Aerodactyl',
            self::SNORLAX => 'Snorlax',
            self::ARTICUNO => 'Articuno',
            self::ZAPDOS => 'Zapdos',
            self::MOLTRES => 'Moltres',
            self::DRATINI => 'Dratini',
            self::DRAGONAIR => 'Dragonair',
            self::DRAGONITE => 'Dragonite',
            self::MEWTWO => 'Mewtwo',
            self::MEW => 'Mew',
        };
    }

    public function slug(): string
    {
        return match ($this) {
            self::BULBASAUR => 'bulbasaur',
            self::IVYSAUR => 'ivysaur',
            self::VENUSAUR => 'venusaur',
            self::CHARMANDER => 'charmander',
            self::CHARMELEON => 'charmeleon',
            self::CHARIZARD => 'charizard',
            self::SQUIRTLE => 'squirtle',
            self::WARTORTLE => 'wartortle',
            self::BLASTOISE => 'blastoise',
            self::CATERPIE => 'caterpie',
            self::METAPOD => 'metapod',
            self::BUTTERFREE => 'butterfree',
            self::WEEDLE => 'weedle',
            self::KAKUNA => 'kakuna',
            self::BEEDRILL => 'beedrill',
            self::PIDGEY => 'pidgey',
            self::PIDGEOTTO => 'pidgeotto',
            self::PIDGEOT => 'pidgeot',
            self::RATTATA => 'rattata',
            self::RATICATE => 'raticate',
            self::SPEAROW => 'spearow',
            self::FEAROW => 'fearow',
            self::EKANS => 'ekans',
            self::ARBOK => 'arbok',
            self::PIKACHU => 'pikachu',
            self::RAICHU => 'raichu',
            self::SANDSHREW => 'sandshrew',
            self::SANDSLASH => 'sandslash',
            self::NIDORAN_FEMALE => 'nidoran-f',
            self::NIDORINA => 'nidorina',
            self::NIDOQUEEN => 'nidoqueen',
            self::NIDORAN_MALE => 'nidoran-m',
            self::NIDORINO => 'nidorino',
            self::NIDOKING => 'nidoking',
            self::CLEFAIRY => 'clefairy',
            self::CLEFABLE => 'clefable',
            self::VULPIX => 'vulpix',
            self::NINETALES => 'ninetales',
            self::JIGGLYPUFF => 'jigglypuff',
            self::WIGGLYTUFF => 'wigglytuff',
            self::ZUBAT => 'zubat',
            self::GOLBAT => 'golbat',
            self::ODDISH => 'oddish',
            self::GLOOM => 'gloom',
            self::VILEPLUME => 'vileplume',
            self::PARAS => 'paras',
            self::PARASECT => 'parasect',
            self::VENONAT => 'venonat',
            self::VENOMOTH => 'venomoth',
            self::DIGLETT => 'diglett',
            self::DUGTRIO => 'dugtrio',
            self::MEOWTH => 'meowth',
            self::PERSIAN => 'persian',
            self::PSYDUCK => 'psyduck',
            self::GOLDUCK => 'golduck',
            self::MANKEY => 'mankey',
            self::PRIMEAPE => 'primeape',
            self::GROWLITHE => 'growlithe',
            self::ARCANINE => 'arcanine',
            self::POLIWAG => 'poliwag',
            self::POLIWHIRL => 'poliwhirl',
            self::POLIWRATH => 'poliwrath',
            self::ABRA => 'abra',
            self::KADABRA => 'kadabra',
            self::ALAKAZAM => 'alakazam',
            self::MACHOP => 'machop',
            self::MACHOKE => 'machoke',
            self::MACHAMP => 'machamp',
            self::BELLSPROUT => 'bellsprout',
            self::WEEPINBELL => 'weepinbell',
            self::VICTREEBEL => 'victreebel',
            self::TENTACOOL => 'tentacool',
            self::TENTACRUEL => 'tentacruel',
            self::GEODUDE => 'geodude',
            self::GRAVELER => 'graveler',
            self::GOLEM => 'golem',
            self::PONYTA => 'ponyta',
            self::RAPIDASH => 'rapidash',
            self::SLOWPOKE => 'slowpoke',
            self::SLOWBRO => 'slowbro',
            self::MAGNEMITE => 'magnemite',
            self::MAGNETON => 'magneton',
            self::FARFETCHD => 'farfetchd',
            self::DODUO => 'doduo',
            self::DODRIO => 'dodrio',
            self::SEEL => 'seel',
            self::DEWGONG => 'dewgong',
            self::GRIMER => 'grimer',
            self::MUK => 'muk',
            self::SHELLDER => 'shellder',
            self::CLOYSTER => 'cloyster',
            self::GASTLY => 'gastly',
            self::HAUNTER => 'haunter',
            self::GENGAR => 'gengar',
            self::ONIX => 'onix',
            self::DROWZEE => 'drowzee',
            self::HYPNO => 'hypno',
            self::KRABBY => 'krabby',
            self::KINGLER => 'kingler',
            self::VOLTORB => 'voltorb',
            self::ELECTRODE => 'electrode',
            self::EXEGGCUTE => 'exeggcute',
            self::EXEGGUTOR => 'exeggutor',
            self::CUBONE => 'cubone',
            self::MAROWAK => 'marowak',
            self::HITMONLEE => 'hitmonlee',
            self::HITMONCHAN => 'hitmonchan',
            self::LICKITUNG => 'lickitung',
            self::KOFFING => 'koffing',
            self::WEEZING => 'weezing',
            self::RHYHORN => 'rhyhorn',
            self::RHYDON => 'rhydon',
            self::CHANSEY => 'chansey',
            self::TANGELA => 'tangela',
            self::KANGASKHAN => 'kangaskhan',
            self::HORSEA => 'horsea',
            self::SEADRA => 'seadra',
            self::GOLDEEN => 'goldeen',
            self::SEAKING => 'seaking',
            self::STARYU => 'staryu',
            self::STARMIE => 'starmie',
            self::MR_MIME => 'mr-mime',
            self::SCYTHER => 'scyther',
            self::JYNX => 'jynx',
            self::ELECTABUZZ => 'electabuzz',
            self::MAGMAR => 'magmar',
            self::PINSIR => 'pinsir',
            self::TAUROS => 'tauros',
            self::MAGIKARP => 'magikarp',
            self::GYARADOS => 'gyarados',
            self::LAPRAS => 'lapras',
            self::DITTO => 'ditto',
            self::EEVEE => 'eevee',
            self::VAPOREON => 'vaporeon',
            self::JOLTEON => 'jolteon',
            self::FLAREON => 'flareon',
            self::PORYGON => 'porygon',
            self::OMANYTE => 'omanyte',
            self::OMASTAR => 'omastar',
            self::KABUTO => 'kabuto',
            self::KABUTOPS => 'kabutops',
            self::AERODACTYL => 'aerodactyl',
            self::SNORLAX => 'snorlax',
            self::ARTICUNO => 'articuno',
            self::ZAPDOS => 'zapdos',
            self::MOLTRES => 'moltres',
            self::DRATINI => 'dratini',
            self::DRAGONAIR => 'dragonair',
            self::DRAGONITE => 'dragonite',
            self::MEWTWO => 'mewtwo',
            self::MEW => 'mew',
        };
    }
}
