<?php

declare(strict_types=1);

namespace App\Enums;

/*
* The number here represents the national dex number of the Pokemon.
*/
enum Gen2Pokemon: int
{
    case CHIKORITA = 152;
    case BAYLEEF = 153;
    case MEGANIUM = 154;
    case CYNDAQUIL = 155;
    case QUILAVA = 156;
    case TYPHLOSION = 157;
    case TOTODILE = 158;
    case CROCONAW = 159;
    case FERALIGATR = 160;
    case SENTRET = 161;
    case FURRET = 162;
    case HOOTHOOT = 163;
    case NOCTOWL = 164;
    case LEDYBA = 165;
    case LEDIAN = 166;
    case SPINARAK = 167;
    case ARIADOS = 168;
    case CROBAT = 169;
    case CHINCHOU = 170;
    case LANTURN = 171;
    case PICHU = 172;
    case CLEFFA = 173;
    case IGGLYBUFF = 174;
    case TOGEPI = 175;
    case TOGETIC = 176;
    case NATU = 177;
    case XATU = 178;
    case MAREEP = 179;
    case FLAAFFY = 180;
    case AMPHAROS = 181;
    case BELLOSSOM = 182;
    case MARILL = 183;
    case AZUMARILL = 184;
    case SUDOWOODO = 185;
    case POLITOED = 186;
    case HOPPIP = 187;
    case SKIPLOOM = 188;
    case JUMPLUFF = 189;
    case AIPOM = 190;
    case SUNKERN = 191;
    case SUNFLORA = 192;
    case YANMA = 193;
    case WOOPER = 194;
    case QUAGSIRE = 195;
    case ESPEON = 196;
    case UMBREON = 197;
    case MURKROW = 198;
    case SLOWKING = 199;
    case MISDREAVUS = 200;
    case UNOWN = 201;
    case WOBBUFFET = 202;
    case GIRAFARIG = 203;
    case PINECO = 204;
    case FORRETRESS = 205;
    case DUNSPARCE = 206;
    case GLIGAR = 207;
    case STEELIX = 208;
    case SNUBBULL = 209;
    case GRANBULL = 210;
    case QWILFISH = 211;
    case SCIZOR = 212;
    case SHUCKLE = 213;
    case HERACROSS = 214;
    case SNEASEL = 215;
    case TEDDIURSA = 216;
    case URSARING = 217;
    case SLUGMA = 218;
    case MAGCARGO = 219;
    case SWINUB = 220;
    case PILOSWINE = 221;
    case CORSOLA = 222;
    case REMORAID = 223;
    case OCTILLERY = 224;
    case DELIBIRD = 225;
    case MANTINE = 226;
    case SKARMORY = 227;
    case HOUNDOUR = 228;
    case HOUNDOOM = 229;
    case KINGDRA = 230;
    case PHANPY = 231;
    case DONPHAN = 232;
    case PORYGON2 = 233;
    case STANTLER = 234;
    case SMEARGLE = 235;
    case TYROGUE = 236;
    case HITMONTOP = 237;
    case SMOOCHUM = 238;
    case ELEKID = 239;
    case MAGBY = 240;
    case MILTANK = 241;
    case BLISSEY = 242;
    case RAIKOU = 243;
    case ENTEI = 244;
    case SUICUNE = 245;
    case LARVITAR = 246;
    case PUPITAR = 247;
    case TYRANITAR = 248;
    case LUGIA = 249;
    case HO_OH = 250;
    case CELEBI = 251;

    public function evolvesFrom(): self|Gen1Pokemon|Gen3Pokemon|Gen4Pokemon|null
    {
        return match ($this) {
            self::BAYLEEF => self::CHIKORITA,
            self::MEGANIUM => self::BAYLEEF,
            self::QUILAVA => self::CYNDAQUIL,
            self::TYPHLOSION => self::QUILAVA,
            self::CROCONAW => self::TOTODILE,
            self::FERALIGATR => self::CROCONAW,
            self::FURRET => self::SENTRET,
            self::NOCTOWL => self::HOOTHOOT,
            self::LEDIAN => self::LEDYBA,
            self::ARIADOS => self::SPINARAK,
            self::CROBAT => Gen1Pokemon::GOLBAT,
            self::LANTURN => self::CHINCHOU,
            self::TOGETIC => self::TOGEPI,
            self::XATU => self::NATU,
            self::FLAAFFY => self::MAREEP,
            self::AMPHAROS => self::FLAAFFY,
            self::BELLOSSOM => Gen1Pokemon::GLOOM,
            self::MARILL => Gen3Pokemon::AZURILL,
            self::AZUMARILL => self::MARILL,
            self::SUDOWOODO => Gen4Pokemon::BONSLY,
            self::POLITOED => Gen1Pokemon::POLIWHIRL,
            self::SKIPLOOM => self::HOPPIP,
            self::JUMPLUFF => self::SKIPLOOM,
            self::SUNFLORA => self::SUNKERN,
            self::QUAGSIRE => self::WOOPER,
            self::ESPEON => Gen1Pokemon::EEVEE,
            self::UMBREON => Gen1Pokemon::EEVEE,
            self::SLOWKING => Gen1Pokemon::SLOWBRO,
            self::WOBBUFFET => Gen3Pokemon::WYNAUT,
            self::FORRETRESS => self::PINECO,
            self::STEELIX => Gen1Pokemon::ONIX,
            self::GRANBULL => self::SNUBBULL,
            self::SCIZOR => Gen1Pokemon::SCYTHER,
            self::URSARING => self::TEDDIURSA,
            self::MAGCARGO => self::SLUGMA,
            self::PILOSWINE => self::SWINUB,
            self::OCTILLERY => self::REMORAID,
            self::MANTINE => Gen4Pokemon::MANTYKE,
            self::HOUNDOOM => self::HOUNDOUR,
            self::KINGDRA => Gen1Pokemon::SEADRA,
            self::DONPHAN => self::PHANPY,
            self::PORYGON2 => Gen1Pokemon::PORYGON,
            self::HITMONTOP => self::TYROGUE,
            self::BLISSEY => Gen1Pokemon::CHANSEY,
            self::PUPITAR => self::LARVITAR,
            self::TYRANITAR => self::PUPITAR,
            default => null,

        };
    }

    public function name(): string
    {
        return match ($this) {
            self::CHIKORITA => 'Chikorita',
            self::BAYLEEF => 'Bayleef',
            self::MEGANIUM => 'Meganium',
            self::CYNDAQUIL => 'Cyndaquil',
            self::QUILAVA => 'Quilava',
            self::TYPHLOSION => 'Typhlosion',
            self::TOTODILE => 'Totodile',
            self::CROCONAW => 'Croconaw',
            self::FERALIGATR => 'Feraligatr',
            self::SENTRET => 'Sentret',
            self::FURRET => 'Furret',
            self::HOOTHOOT => 'Hoothoot',
            self::NOCTOWL => 'Noctowl',
            self::LEDYBA => 'Ledyba',
            self::LEDIAN => 'Ledian',
            self::SPINARAK => 'Spinarak',
            self::ARIADOS => 'Ariados',
            self::CROBAT => 'Crobat',
            self::CHINCHOU => 'Chinchou',
            self::LANTURN => 'Lanturn',
            self::PICHU => 'Pichu',
            self::CLEFFA => 'Cleffa',
            self::IGGLYBUFF => 'Igglybuff',
            self::TOGEPI => 'Togepi',
            self::TOGETIC => 'Togetic',
            self::NATU => 'Natu',
            self::XATU => 'Xatu',
            self::MAREEP => 'Mareep',
            self::FLAAFFY => 'Flaaffy',
            self::AMPHAROS => 'Ampharos',
            self::BELLOSSOM => 'Bellossom',
            self::MARILL => 'Marill',
            self::AZUMARILL => 'Azumarill',
            self::SUDOWOODO => 'Sudowoodo',
            self::POLITOED => 'Politoed',
            self::HOPPIP => 'Hoppip',
            self::SKIPLOOM => 'Skiploom',
            self::JUMPLUFF => 'Jumpluff',
            self::AIPOM => 'Aipom',
            self::SUNKERN => 'Sunkern',
            self::SUNFLORA => 'Sunflora',
            self::YANMA => 'Yanma',
            self::WOOPER => 'Wooper',
            self::QUAGSIRE => 'Quagsire',
            self::ESPEON => 'Espeon',
            self::UMBREON => 'Umbreon',
            self::MURKROW => 'Murkrow',
            self::SLOWKING => 'Slowking',
            self::MISDREAVUS => 'Misdreavus',
            self::UNOWN => 'Unown',
            self::WOBBUFFET => 'Wobbuffet',
            self::GIRAFARIG => 'Girafarig',
            self::PINECO => 'Pineco',
            self::FORRETRESS => 'Forretress',
            self::DUNSPARCE => 'Dunsparce',
            self::GLIGAR => 'Gligar',
            self::STEELIX => 'Steelix',
            self::SNUBBULL => 'Snubbull',
            self::GRANBULL => 'Granbull',
            self::QWILFISH => 'Qwilfish',
            self::SCIZOR => 'Scizor',
            self::SHUCKLE => 'Shuckle',
            self::HERACROSS => 'Heracross',
            self::SNEASEL => 'Sneasel',
            self::TEDDIURSA => 'Teddiursa',
            self::URSARING => 'Ursaring',
            self::SLUGMA => 'Slugma',
            self::MAGCARGO => 'Magcargo',
            self::SWINUB => 'Swinub',
            self::PILOSWINE => 'Piloswine',
            self::CORSOLA => 'Corsola',
            self::REMORAID => 'Remoraid',
            self::OCTILLERY => 'Octillery',
            self::DELIBIRD => 'Delibird',
            self::MANTINE => 'Mantine',
            self::SKARMORY => 'Skarmory',
            self::HOUNDOUR => 'Houndour',
            self::HOUNDOOM => 'Houndoom',
            self::KINGDRA => 'Kingdra',
            self::PHANPY => 'Phanpy',
            self::DONPHAN => 'Donphan',
            self::PORYGON2 => 'Porygon2',
            self::STANTLER => 'Stantler',
            self::SMEARGLE => 'Smeargle',
            self::TYROGUE => 'Tyrogue',
            self::HITMONTOP => 'Hitmontop',
            self::SMOOCHUM => 'Smoochum',
            self::ELEKID => 'Elekid',
            self::MAGBY => 'Magby',
            self::MILTANK => 'Miltank',
            self::BLISSEY => 'Blissey',
            self::RAIKOU => 'Raikou',
            self::ENTEI => 'Entei',
            self::SUICUNE => 'Suicune',
            self::LARVITAR => 'Larvitar',
            self::PUPITAR => 'Pupitar',
            self::TYRANITAR => 'Tyranitar',
            self::LUGIA => 'Lugia',
            self::HO_OH => 'Ho-Oh',
            self::CELEBI => 'Celebi',

        };
    }

    public function slug(): string
    {
        return match ($this) {
            self::CHIKORITA => 'chikorita',
            self::BAYLEEF => 'bayleef',
            self::MEGANIUM => 'meganium',
            self::CYNDAQUIL => 'cyndaquil',
            self::QUILAVA => 'quilava',
            self::TYPHLOSION => 'typhlosion',
            self::TOTODILE => 'totodile',
            self::CROCONAW => 'croconaw',
            self::FERALIGATR => 'feraligatr',
            self::SENTRET => 'sentret',
            self::FURRET => 'furret',
            self::HOOTHOOT => 'hoothoot',
            self::NOCTOWL => 'noctowl',
            self::LEDYBA => 'ledyba',
            self::LEDIAN => 'ledian',
            self::SPINARAK => 'spinarak',
            self::ARIADOS => 'ariados',
            self::CROBAT => 'crobat',
            self::CHINCHOU => 'chinchou',
            self::LANTURN => 'lanturn',
            self::PICHU => 'pichu',
            self::CLEFFA => 'cleffa',
            self::IGGLYBUFF => 'igglybuff',
            self::TOGEPI => 'togepi',
            self::TOGETIC => 'togetic',
            self::NATU => 'natu',
            self::XATU => 'xatu',
            self::MAREEP => 'mareep',
            self::FLAAFFY => 'flaaffy',
            self::AMPHAROS => 'ampharos',
            self::BELLOSSOM => 'bellossom',
            self::MARILL => 'marill',
            self::AZUMARILL => 'azumarill',
            self::SUDOWOODO => 'sudowoodo',
            self::POLITOED => 'politoed',
            self::HOPPIP => 'hoppip',
            self::SKIPLOOM => 'skiploom',
            self::JUMPLUFF => 'jumpluff',
            self::AIPOM => 'aipom',
            self::SUNKERN => 'sunkern',
            self::SUNFLORA => 'sunflora',
            self::YANMA => 'yanma',
            self::WOOPER => 'wooper',
            self::QUAGSIRE => 'quagsire',
            self::ESPEON => 'espeon',
            self::UMBREON => 'umbreon',
            self::MURKROW => 'murkrow',
            self::SLOWKING => 'slowking',
            self::MISDREAVUS => 'misdreavus',
            self::UNOWN => 'unown',
            self::WOBBUFFET => 'wobbuffet',
            self::GIRAFARIG => 'girafarig',
            self::PINECO => 'pineco',
            self::FORRETRESS => 'forretress',
            self::DUNSPARCE => 'dunsparce',
            self::GLIGAR => 'gligar',
            self::STEELIX => 'steelix',
            self::SNUBBULL => 'snubbull',
            self::GRANBULL => 'granbull',
            self::QWILFISH => 'qwilfish',
            self::SCIZOR => 'scizor',
            self::SHUCKLE => 'shuckle',
            self::HERACROSS => 'heracross',
            self::SNEASEL => 'sneasel',
            self::TEDDIURSA => 'teddiursa',
            self::URSARING => 'ursaring',
            self::SLUGMA => 'slugma',
            self::MAGCARGO => 'magcargo',
            self::SWINUB => 'swinub',
            self::PILOSWINE => 'piloswine',
            self::CORSOLA => 'corsola',
            self::REMORAID => 'remoraid',
            self::OCTILLERY => 'octillery',
            self::DELIBIRD => 'delibird',
            self::MANTINE => 'mantine',
            self::SKARMORY => 'skarmory',
            self::HOUNDOUR => 'houndour',
            self::HOUNDOOM => 'houndoom',
            self::KINGDRA => 'kingdra',
            self::PHANPY => 'phanpy',
            self::DONPHAN => 'donphan',
            self::PORYGON2 => 'porygon2',
            self::STANTLER => 'stantler',
            self::SMEARGLE => 'smeargle',
            self::TYROGUE => 'tyrogue',
            self::HITMONTOP => 'hitmontop',
            self::SMOOCHUM => 'smoochum',
            self::ELEKID => 'elekid',
            self::MAGBY => 'magby',
            self::MILTANK => 'miltank',
            self::BLISSEY => 'blissey',
            self::RAIKOU => 'raikou',
            self::ENTEI => 'entei',
            self::SUICUNE => 'suicune',
            self::LARVITAR => 'larvitar',
            self::PUPITAR => 'pupitar',
            self::TYRANITAR => 'tyranitar',
            self::LUGIA => 'lugia',
            self::HO_OH => 'ho-oh',
            self::CELEBI => 'celebi',
        };
    }
}
