<?php

declare(strict_types=1);

namespace App\Enums;

/*
* The number here represents the national dex number of the Pokemon.
*/
enum Gen3Pokemon: int
{
    case TREECKO = 252;
    case GROVYLE = 253;
    case SCEPTILE = 254;
    case TORCHIC = 255;
    case COMBUSKEN = 256;
    case BLAZIKEN = 257;
    case MUDKIP = 258;
    case MARSHTOMP = 259;
    case SWAMPERT = 260;
    case POOCHYENA = 261;
    case MIGHTYENA = 262;
    case ZIGZAGOON = 263;
    case LINOONE = 264;
    case WURMPLE = 265;
    case SILCOON = 266;
    case BEAUTIFLY = 267;
    case CASCOON = 268;
    case DUSTOX = 269;
    case LOTAD = 270;
    case LOMBRE = 271;
    case LUDICOLO = 272;
    case SEEDOT = 273;
    case NUZLEAF = 274;
    case SHIFTRY = 275;
    case TAILLOW = 276;
    case SWELLOW = 277;
    case WINGULL = 278;
    case PELIPPER = 279;
    case RALTS = 280;
    case KIRLIA = 281;
    case GARDEVOIR = 282;
    case SURSKIT = 283;
    case MASQUERAIN = 284;
    case SHROOMISH = 285;
    case BRELOOM = 286;
    case SLAKOTH = 287;
    case VIGOROTH = 288;
    case SLAKING = 289;
    case NINCADA = 290;
    case NINJASK = 291;
    case SHEDINJA = 292;
    case WHISMUR = 293;
    case LOUDRED = 294;
    case EXPLOUD = 295;
    case MAKUHITA = 296;
    case HARIYAMA = 297;
    case AZURILL = 298;
    case NOSEPASS = 299;
    case SKITTY = 300;
    case DELCATTY = 301;
    case SABLEYE = 302;
    case MAWILE = 303;
    case ARON = 304;
    case LAIRON = 305;
    case AGGRON = 306;
    case MEDITITE = 307;
    case MEDICHAM = 308;
    case ELECTRIKE = 309;
    case MANECTRIC = 310;
    case PLUSLE = 311;
    case MINUN = 312;
    case VOLBEAT = 313;
    case ILLUMISE = 314;
    case ROSELIA = 315;
    case GULPIN = 316;
    case SWALOT = 317;
    case CARVANHA = 318;
    case SHARPEDO = 319;
    case WAILMER = 320;
    case WAILORD = 321;
    case NUMEL = 322;
    case CAMERUPT = 323;
    case TORKOAL = 324;
    case SPOINK = 325;
    case GRUMPIG = 326;
    case SPINDA = 327;
    case TRAPINCH = 328;
    case VIBRAVA = 329;
    case FLYGON = 330;
    case CACNEA = 331;
    case CACTURNE = 332;
    case SWABLU = 333;
    case ALTARIA = 334;
    case ZANGOOSE = 335;
    case SEVIPER = 336;
    case LUNATONE = 337;
    case SOLROCK = 338;
    case BARBOACH = 339;
    case WHISCASH = 340;
    case CORPHISH = 341;
    case CRAWDAUNT = 342;
    case BALTOY = 343;
    case CLAYDOL = 344;
    case LILEEP = 345;
    case CRADILY = 346;
    case ANORITH = 347;
    case ARMALDO = 348;
    case FEEBAS = 349;
    case MILOTIC = 350;
    case CASTFORM = 351;
    case KECLEON = 352;
    case SHUPPET = 353;
    case BANETTE = 354;
    case DUSKULL = 355;
    case DUSCLOPS = 356;
    case TROPIUS = 357;
    case CHIMECHO = 358;
    case ABSOL = 359;
    case WYNAUT = 360;
    case SNORUNT = 361;
    case GLALIE = 362;
    case SPHEAL = 363;
    case SEALEO = 364;
    case WALREIN = 365;
    case CLAMPERL = 366;
    case HUNTAIL = 367;
    case GOREBYSS = 368;
    case RELICANTH = 369;
    case LUVDISC = 370;
    case BAGON = 371;
    case SHELGON = 372;
    case SALAMENCE = 373;
    case BELDUM = 374;
    case METANG = 375;
    case METAGROSS = 376;
    case REGIROCK = 377;
    case REGICE = 378;
    case REGISTEEL = 379;
    case LATIAS = 380;
    case LATIOS = 381;
    case KYOGRE = 382;
    case GROUDON = 383;
    case RAYQUAZA = 384;
    case JIRACHI = 385;
    case DEOXYS = 386;

    public function generation(): Generation
    {
        return Generation::III;
    }

    public function name(): string
    {
        return match ($this) {
            self::TREECKO => 'Treecko',
            self::GROVYLE => 'Grovyle',
            self::SCEPTILE => 'Sceptile',
            self::TORCHIC => 'Torchic',
            self::COMBUSKEN => 'Combusken',
            self::BLAZIKEN => 'Blaziken',
            self::MUDKIP => 'Mudkip',
            self::MARSHTOMP => 'Marshtomp',
            self::SWAMPERT => 'Swampert',
            self::POOCHYENA => 'Poochyena',
            self::MIGHTYENA => 'Mightyena',
            self::ZIGZAGOON => 'Zigzagoon',
            self::LINOONE => 'Linoone',
            self::WURMPLE => 'Wurmple',
            self::SILCOON => 'Silcoon',
            self::BEAUTIFLY => 'Beautifly',
            self::CASCOON => 'Cascoon',
            self::DUSTOX => 'Dustox',
            self::LOTAD => 'Lotad',
            self::LOMBRE => 'Lombre',
            self::LUDICOLO => 'Ludicolo',
            self::SEEDOT => 'Seedot',
            self::NUZLEAF => 'Nuzleaf',
            self::SHIFTRY => 'Shiftry',
            self::TAILLOW => 'Taillow',
            self::SWELLOW => 'Swellow',
            self::WINGULL => 'Wingull',
            self::PELIPPER => 'Pelipper',
            self::RALTS => 'Ralts',
            self::KIRLIA => 'Kirlia',
            self::GARDEVOIR => 'Gardevoir',
            self::SURSKIT => 'Surskit',
            self::MASQUERAIN => 'Masquerain',
            self::SHROOMISH => 'Shroomish',
            self::BRELOOM => 'Breloom',
            self::SLAKOTH => 'Slakoth',
            self::VIGOROTH => 'Vigoroth',
            self::SLAKING => 'Slaking',
            self::NINCADA => 'Nincada',
            self::NINJASK => 'Ninjask',
            self::SHEDINJA => 'Shedinja',
            self::WHISMUR => 'Whismur',
            self::LOUDRED => 'Loudred',
            self::EXPLOUD => 'Exploud',
            self::MAKUHITA => 'Makuhita',
            self::HARIYAMA => 'Hariyama',
            self::AZURILL => 'Azurill',
            self::NOSEPASS => 'Nosepass',
            self::SKITTY => 'Skitty',
            self::DELCATTY => 'Delcatty',
            self::SABLEYE => 'Sableye',
            self::MAWILE => 'Mawile',
            self::ARON => 'Aron',
            self::LAIRON => 'Lairon',
            self::AGGRON => 'Aggron',
            self::MEDITITE => 'Meditite',
            self::MEDICHAM => 'Medicham',
            self::ELECTRIKE => 'Electrike',
            self::MANECTRIC => 'Manectric',
            self::PLUSLE => 'Plusle',
            self::MINUN => 'Minun',
            self::VOLBEAT => 'Volbeat',
            self::ILLUMISE => 'Illumise',
            self::ROSELIA => 'Roselia',
            self::GULPIN => 'Gulpin',
            self::SWALOT => 'Swalot',
            self::CARVANHA => 'Carvanha',
            self::SHARPEDO => 'Sharpedo',
            self::WAILMER => 'Wailmer',
            self::WAILORD => 'Wailord',
            self::NUMEL => 'Numel',
            self::CAMERUPT => 'Camerupt',
            self::TORKOAL => 'Torkoal',
            self::SPOINK => 'Spoink',
            self::GRUMPIG => 'Grumpig',
            self::SPINDA => 'Spinda',
            self::TRAPINCH => 'Trapinch',
            self::VIBRAVA => 'Vibrava',
            self::FLYGON => 'Flygon',
            self::CACNEA => 'Cacnea',
            self::CACTURNE => 'Cacturne',
            self::SWABLU => 'Swablu',
            self::ALTARIA => 'Altaria',
            self::ZANGOOSE => 'Zangoose',
            self::SEVIPER => 'Seviper',
            self::LUNATONE => 'Lunatone',
            self::SOLROCK => 'Solrock',
            self::BARBOACH => 'Barboach',
            self::WHISCASH => 'Whiscash',
            self::CORPHISH => 'Corphish',
            self::CRAWDAUNT => 'Crawdaunt',
            self::BALTOY => 'Baltoy',
            self::CLAYDOL => 'Claydol',
            self::LILEEP => 'Lileep',
            self::CRADILY => 'Cradily',
            self::ANORITH => 'Anorith',
            self::ARMALDO => 'Armaldo',
            self::FEEBAS => 'Feebas',
            self::MILOTIC => 'Milotic',
            self::CASTFORM => 'Castform',
            self::KECLEON => 'Kecleon',
            self::SHUPPET => 'Shuppet',
            self::BANETTE => 'Banette',
            self::DUSKULL => 'Duskull',
            self::DUSCLOPS => 'Dusclops',
            self::TROPIUS => 'Tropius',
            self::CHIMECHO => 'Chimecho',
            self::ABSOL => 'Absol',
            self::WYNAUT => 'Wynaut',
            self::SNORUNT => 'Snorunt',
            self::GLALIE => 'Glalie',
            self::SPHEAL => 'Spheal',
            self::SEALEO => 'Sealeo',
            self::WALREIN => 'Walrein',
            self::CLAMPERL => 'Clamperl',
            self::HUNTAIL => 'Huntail',
            self::GOREBYSS => 'Gorebyss',
            self::RELICANTH => 'Relicanth',
            self::LUVDISC => 'Luvdisc',
            self::BAGON => 'Bagon',
            self::SHELGON => 'Shelgon',
            self::SALAMENCE => 'Salamence',
            self::BELDUM => 'Beldum',
            self::METANG => 'Metang',
            self::METAGROSS => 'Metagross',
            self::REGIROCK => 'Regirock',
            self::REGICE => 'Regice',
            self::REGISTEEL => 'Registeel',
            self::LATIAS => 'Latias',
            self::LATIOS => 'Latios',
            self::KYOGRE => 'Kyogre',
            self::GROUDON => 'Groudon',
            self::RAYQUAZA => 'Rayquaza',
            self::JIRACHI => 'Jirachi',
            self::DEOXYS => 'Deoxys',
        };
    }

    public function slug(): string
    {
        return match ($this) {
            self::TREECKO => 'treecko',
            self::GROVYLE => 'grovyle',
            self::SCEPTILE => 'sceptile',
            self::TORCHIC => 'torchic',
            self::COMBUSKEN => 'combusken',
            self::BLAZIKEN => 'blaziken',
            self::MUDKIP => 'mudkip',
            self::MARSHTOMP => 'marshtomp',
            self::SWAMPERT => 'swampert',
            self::POOCHYENA => 'poochyena',
            self::MIGHTYENA => 'mightyena',
            self::ZIGZAGOON => 'zigzagoon',
            self::LINOONE => 'linoone',
            self::WURMPLE => 'wurmple',
            self::SILCOON => 'silcoon',
            self::BEAUTIFLY => 'beautifly',
            self::CASCOON => 'cascoon',
            self::DUSTOX => 'dustox',
            self::LOTAD => 'lotad',
            self::LOMBRE => 'lombre',
            self::LUDICOLO => 'ludicolo',
            self::SEEDOT => 'seedot',
            self::NUZLEAF => 'nuzleaf',
            self::SHIFTRY => 'shiftry',
            self::TAILLOW => 'taillow',
            self::SWELLOW => 'swellow',
            self::WINGULL => 'wingull',
            self::PELIPPER => 'pelipper',
            self::RALTS => 'ralts',
            self::KIRLIA => 'kirlia',
            self::GARDEVOIR => 'gardevoir',
            self::SURSKIT => 'surskit',
            self::MASQUERAIN => 'masquerain',
            self::SHROOMISH => 'shroomish',
            self::BRELOOM => 'breloom',
            self::SLAKOTH => 'slakoth',
            self::VIGOROTH => 'vigoroth',
            self::SLAKING => 'slaking',
            self::NINCADA => 'nincada',
            self::NINJASK => 'ninjask',
            self::SHEDINJA => 'shedinja',
            self::WHISMUR => 'whismur',
            self::LOUDRED => 'loudred',
            self::EXPLOUD => 'exploud',
            self::MAKUHITA => 'makuhita',
            self::HARIYAMA => 'hariyama',
            self::AZURILL => 'azurill',
            self::NOSEPASS => 'nosepass',
            self::SKITTY => 'skitty',
            self::DELCATTY => 'delcatty',
            self::SABLEYE => 'sableye',
            self::MAWILE => 'mawile',
            self::ARON => 'aron',
            self::LAIRON => 'lairon',
            self::AGGRON => 'aggron',
            self::MEDITITE => 'meditite',
            self::MEDICHAM => 'medicham',
            self::ELECTRIKE => 'electrike',
            self::MANECTRIC => 'manectric',
            self::PLUSLE => 'plusle',
            self::MINUN => 'minun',
            self::VOLBEAT => 'volbeat',
            self::ILLUMISE => 'illumise',
            self::ROSELIA => 'roselia',
            self::GULPIN => 'gulpin',
            self::SWALOT => 'swalot',
            self::CARVANHA => 'carvanha',
            self::SHARPEDO => 'sharpedo',
            self::WAILMER => 'wailmer',
            self::WAILORD => 'wailord',
            self::NUMEL => 'numel',
            self::CAMERUPT => 'camerupt',
            self::TORKOAL => 'torkoal',
            self::SPOINK => 'spoink',
            self::GRUMPIG => 'grumpig',
            self::SPINDA => 'spinda',
            self::TRAPINCH => 'trapinch',
            self::VIBRAVA => 'vibrava',
            self::FLYGON => 'flygon',
            self::CACNEA => 'cacnea',
            self::CACTURNE => 'cacturne',
            self::SWABLU => 'swablu',
            self::ALTARIA => 'altaria',
            self::ZANGOOSE => 'zangoose',
            self::SEVIPER => 'seviper',
            self::LUNATONE => 'lunatone',
            self::SOLROCK => 'solrock',
            self::BARBOACH => 'barboach',
            self::WHISCASH => 'whiscash',
            self::CORPHISH => 'corphish',
            self::CRAWDAUNT => 'crawdaunt',
            self::BALTOY => 'baltoy',
            self::CLAYDOL => 'claydol',
            self::LILEEP => 'lileep',
            self::CRADILY => 'cradily',
            self::ANORITH => 'anorith',
            self::ARMALDO => 'armaldo',
            self::FEEBAS => 'feebas',
            self::MILOTIC => 'milotic',
            self::CASTFORM => 'castform',
            self::KECLEON => 'kecleon',
            self::SHUPPET => 'shuppet',
            self::BANETTE => 'banette',
            self::DUSKULL => 'duskull',
            self::DUSCLOPS => 'dusclops',
            self::TROPIUS => 'tropius',
            self::CHIMECHO => 'chimecho',
            self::ABSOL => 'absol',
            self::WYNAUT => 'wynaut',
            self::SNORUNT => 'snorunt',
            self::GLALIE => 'glalie',
            self::SPHEAL => 'spheal',
            self::SEALEO => 'sealeo',
            self::WALREIN => 'walrein',
            self::CLAMPERL => 'clamperl',
            self::HUNTAIL => 'huntail',
            self::GOREBYSS => 'gorebyss',
            self::RELICANTH => 'relicanth',
            self::LUVDISC => 'luvdisc',
            self::BAGON => 'bagon',
            self::SHELGON => 'shelgon',
            self::SALAMENCE => 'salamence',
            self::BELDUM => 'beldum',
            self::METANG => 'metang',
            self::METAGROSS => 'metagross',
            self::REGIROCK => 'regirock',
            self::REGICE => 'regice',
            self::REGISTEEL => 'registeel',
            self::LATIAS => 'latias',
            self::LATIOS => 'latios',
            self::KYOGRE => 'kyogre',
            self::GROUDON => 'groudon',
            self::RAYQUAZA => 'rayquaza',
            self::JIRACHI => 'jirachi',
            self::DEOXYS => 'deoxys',
        }
        ;
    }
}
