<?php

declare(strict_types=1);

namespace App\Enums;

enum Gen5Pokemon: int
{
    case VICTINI = 494;
    case SNIVY = 495;
    case SERVINE = 496;
    case SERPERIOR = 497;
    case TEPIG = 498;
    case PIGNITE = 499;
    case EMBOAR = 500;
    case OSHAWOTT = 501;
    case DEWOTT = 502;
    case SAMUROTT = 503;
    case PATRAT = 504;
    case WATCHOG = 505;
    case LILLIPUP = 506;
    case HERDIER = 507;
    case STOUTLAND = 508;
    case PURRLOIN = 509;
    case LIEPARD = 510;
    case PANSAGE = 511;
    case SIMISAGE = 512;
    case PANSEAR = 513;
    case SIMISEAR = 514;
    case PANPOUR = 515;
    case SIMIPOUR = 516;
    case MUNNA = 517;
    case MUSHARNA = 518;
    case PIDOVE = 519;
    case TRANQUILL = 520;
    case UNFEZANT = 521;
    case BLITZLE = 522;
    case ZEBSTRIKA = 523;
    case ROGGENROLA = 524;
    case BOLDORE = 525;
    case GIGALITH = 526;
    case WOOBAT = 527;
    case SWOOBAT = 528;
    case DRILBUR = 529;
    case EXCADRILL = 530;
    case AUDINO = 531;
    case TIMBURR = 532;
    case GURDURR = 533;
    case CONKELDURR = 534;
    case TYMPOLE = 535;
    case PALPITOAD = 536;
    case SEISMITOAD = 537;
    case THROH = 538;
    case SAWK = 539;
    case SEWADDLE = 540;
    case SWADLOON = 541;
    case LEAVANNY = 542;
    case VENIPEDE = 543;
    case WHIRLIPEDE = 544;
    case SCOLIPEDE = 545;
    case COTTONEE = 546;
    case WHIMSICOTT = 547;
    case PETILIL = 548;
    case LILLIGANT = 549;
    case BASCULIN = 550;
    case SANDILE = 551;
    case KROKOROK = 552;
    case KROOKODILE = 553;
    case DARUMAKA = 554;
    case DARMANITAN = 555;
    case MARACTUS = 556;
    case DWEBBLE = 557;
    case CRUSTLE = 558;
    case SCRAGGY = 559;
    case SCRAFTY = 560;
    case SIGILYPH = 561;
    case YAMASK = 562;
    case COFAGRIGUS = 563;
    case TIRTOUGA = 564;
    case CARRACOSTA = 565;
    case ARCHEN = 566;
    case ARCHEOPS = 567;
    case TRUBBISH = 568;
    case GARBODOR = 569;
    case ZORUA = 570;
    case ZOROARK = 571;
    case MINCCINO = 572;
    case CINCCINO = 573;
    case GOTHITA = 574;
    case GOTHORITA = 575;
    case GOTHITELLE = 576;
    case SOLOSIS = 577;
    case DUOSION = 578;
    case REUNICLUS = 579;
    case DUCKLETT = 580;
    case SWANNA = 581;
    case VANILLITE = 582;
    case VANILLISH = 583;
    case VANILLUXE = 584;
    case DEERLING = 585;
    case SAWSBUCK = 586;
    case EMOLGA = 587;
    case KARRABLAST = 588;
    case ESCAVALIER = 589;
    case FOONGUS = 590;
    case AMOONGUSS = 591;
    case FRILLISH = 592;
    case JELLICENT = 593;
    case ALOMOMOLA = 594;
    case JOLTIK = 595;
    case GALVANTULA = 596;
    case FERROSEED = 597;
    case FERROTHORN = 598;
    case KLINK = 599;
    case KLANG = 600;
    case KLINKLANG = 601;
    case TYNAMO = 602;
    case EELEKTRIK = 603;
    case EELEKTROSS = 604;
    case ELGYEM = 605;
    case BEHEEYEM = 606;
    case LITWICK = 607;
    case LAMPENT = 608;
    case CHANDELURE = 609;
    case AXEW = 610;
    case FRAXURE = 611;
    case HAXORUS = 612;
    case CUBCHOO = 613;
    case BEARTIC = 614;
    case CRYOGONAL = 615;
    case SHELMET = 616;
    case ACCELGOR = 617;
    case STUNFISK = 618;
    case MIENFOO = 619;
    case MIENSHAO = 620;
    case DRUDDIGON = 621;
    case GOLETT = 622;
    case GOLURK = 623;
    case PAWNIARD = 624;
    case BISHARP = 625;
    case BOUFFALANT = 626;
    case RUFFLET = 627;
    case BRAVIARY = 628;
    case VULLABY = 629;
    case MANDIBUZZ = 630;
    case HEATMOR = 631;
    case DURANT = 632;
    case DEINO = 633;
    case ZWEILOUS = 634;
    case HYDREIGON = 635;
    case LARVESTA = 636;
    case VOLCARONA = 637;
    case COBALION = 638;
    case TERRAKION = 639;
    case VIRIZION = 640;
    case TORNADUS = 641;
    case THUNDURUS = 642;
    case RESHIRAM = 643;
    case ZEKROM = 644;
    case LANDORUS = 645;
    case KYUREM = 646;
    case KELDEO = 647;
    case MELOETTA = 648;
    case GENESECT = 649;

    public function generation(): Generation
    {
        return Generation::V;
    }

    public function name(): string
    {
        return match ($this) {
            self::VICTINI => 'Victini',
            self::SNIVY => 'Snivy',
            self::SERVINE => 'Servine',
            self::SERPERIOR => 'Serperior',
            self::TEPIG => 'Tepig',
            self::PIGNITE => 'Pignite',
            self::EMBOAR => 'Emboar',
            self::OSHAWOTT => 'Oshawott',
            self::DEWOTT => 'Dewott',
            self::SAMUROTT => 'Samurott',
            self::PATRAT => 'Patrat',
            self::WATCHOG => 'Watchog',
            self::LILLIPUP => 'Lillipup',
            self::HERDIER => 'Herdier',
            self::STOUTLAND => 'Stoutland',
            self::PURRLOIN => 'Purrloin',
            self::LIEPARD => 'Liepard',
            self::PANSAGE => 'Pansage',
            self::SIMISAGE => 'Simisage',
            self::PANSEAR => 'Pansear',
            self::SIMISEAR => 'Simisear',
            self::PANPOUR => 'Panpour',
            self::SIMIPOUR => 'Simipour',
            self::MUNNA => 'Munna',
            self::MUSHARNA => 'Musharna',
            self::PIDOVE => 'Pidove',
            self::TRANQUILL => 'Tranquill',
            self::UNFEZANT => 'Unfezant',
            self::BLITZLE => 'Blitzle',
            self::ZEBSTRIKA => 'Zebstrika',
            self::ROGGENROLA => 'Roggenrola',
            self::BOLDORE => 'Boldore',
            self::GIGALITH => 'Gigalith',
            self::WOOBAT => 'Woobat',
            self::SWOOBAT => 'Swoobat',
            self::DRILBUR => 'Drilbur',
            self::EXCADRILL => 'Excadrill',
            self::AUDINO => 'Audino',
            self::TIMBURR => 'Timburr',
            self::GURDURR => 'Gurdurr',
            self::CONKELDURR => 'Conkeldurr',
            self::TYMPOLE => 'Tympole',
            self::PALPITOAD => 'Palpitoad',
            self::SEISMITOAD => 'Seismitoad',
            self::THROH => 'Throh',
            self::SAWK => 'Sawk',
            self::SEWADDLE => 'Sewaddle',
            self::SWADLOON => 'Swadloon',
            self::LEAVANNY => 'Leavanny',
            self::VENIPEDE => 'Venipede',
            self::WHIRLIPEDE => 'Whirlipede',
            self::SCOLIPEDE => 'Scolipede',
            self::COTTONEE => 'Cottonee',
            self::WHIMSICOTT => 'Whimsicott',
            self::PETILIL => 'Petilil',
            self::LILLIGANT => 'Lilligant',
            self::BASCULIN => 'Basculin',
            self::SANDILE => 'Sandile',
            self::KROKOROK => 'Krokorok',
            self::KROOKODILE => 'Krookodile',
            self::DARUMAKA => 'Darumaka',
            self::DARMANITAN => 'Darmanitan',
            self::MARACTUS => 'Maractus',
            self::DWEBBLE => 'Dwebble',
            self::CRUSTLE => 'Crustle',
            self::SCRAGGY => 'Scraggy',
            self::SCRAFTY => 'Scrafty',
            self::SIGILYPH => 'Sigilyph',
            self::YAMASK => 'Yamask',
            self::COFAGRIGUS => 'Cofagrigus',
            self::TIRTOUGA => 'Tirtouga',
            self::CARRACOSTA => 'Carracosta',
            self::ARCHEN => 'Archen',
            self::ARCHEOPS => 'Archeops',
            self::TRUBBISH => 'Trubbish',
            self::GARBODOR => 'Garbodor',
            self::ZORUA => 'Zorua',
            self::ZOROARK => 'Zoroark',
            self::MINCCINO => 'Minccino',
            self::CINCCINO => 'Cinccino',
            self::GOTHITA => 'Gothita',
            self::GOTHORITA => 'Gothorita',
            self::GOTHITELLE => 'Gothitelle',
            self::SOLOSIS => 'Solosis',
            self::DUOSION => 'Duosion',
            self::REUNICLUS => 'Reuniclus',
            self::DUCKLETT => 'Ducklett',
            self::SWANNA => 'Swanna',
            self::VANILLITE => 'Vanillite',
            self::VANILLISH => 'Vanillish',
            self::VANILLUXE => 'Vanilluxe',
            self::DEERLING => 'Deerling',
            self::SAWSBUCK => 'Sawsbuck',
            self::EMOLGA => 'Emolga',
            self::KARRABLAST => 'Karrablast',
            self::ESCAVALIER => 'Escavalier',
            self::FOONGUS => 'Foongus',
            self::AMOONGUSS => 'Amoonguss',
            self::FRILLISH => 'Frillish',
            self::JELLICENT => 'Jellicent',
            self::ALOMOMOLA => 'Alomomola',
            self::JOLTIK => 'Joltik',
            self::GALVANTULA => 'Galvantula',
            self::FERROSEED => 'Ferroseed',
            self::FERROTHORN => 'Ferrothorn',
            self::KLINK => 'Klink',
            self::KLANG => 'Klang',
            self::KLINKLANG => 'Klinklang',
            self::TYNAMO => 'Tynamo',
            self::EELEKTRIK => 'Eelektrik',
            self::EELEKTROSS => 'Eelektross',
            self::ELGYEM => 'Elgyem',
            self::BEHEEYEM => 'Beheeyem',
            self::LITWICK => 'Litwick',
            self::LAMPENT => 'Lampent',
            self::CHANDELURE => 'Chandelure',
            self::AXEW => 'Axew',
            self::FRAXURE => 'Fraxure',
            self::HAXORUS => 'Haxorus',
            self::CUBCHOO => 'Cubchoo',
            self::BEARTIC => 'Beartic',
            self::CRYOGONAL => 'Cryogonal',
            self::SHELMET => 'Shelmet',
            self::ACCELGOR => 'Accelgor',
            self::STUNFISK => 'Stunfisk',
            self::MIENFOO => 'Mienfoo',
            self::MIENSHAO => 'Mienshao',
            self::DRUDDIGON => 'Druddigon',
            self::GOLETT => 'Golett',
            self::GOLURK => 'Golurk',
            self::PAWNIARD => 'Pawniard',
            self::BISHARP => 'Bisharp',
            self::BOUFFALANT => 'Bouffalant',
            self::RUFFLET => 'Rufflet',
            self::BRAVIARY => 'Braviary',
            self::VULLABY => 'Vullaby',
            self::MANDIBUZZ => 'Mandibuzz',
            self::HEATMOR => 'Heatmor',
            self::DURANT => 'Durant',
            self::DEINO => 'Deino',
            self::ZWEILOUS => 'Zweilous',
            self::HYDREIGON => 'Hydreigon',
            self::LARVESTA => 'Larvesta',
            self::VOLCARONA => 'Volcarona',
            self::COBALION => 'Cobalion',
            self::TERRAKION => 'Terrakion',
            self::VIRIZION => 'Virizion',
            self::TORNADUS => 'Tornadus',
            self::THUNDURUS => 'Thundurus',
            self::RESHIRAM => 'Reshiram',
            self::ZEKROM => 'Zekrom',
            self::LANDORUS => 'Landorus',
            self::KYUREM => 'Kyurem',
            self::KELDEO => 'Keldeo',
            self::MELOETTA => 'Meloetta',
            self::GENESECT => 'Genesect',
        };
    }

    public function slug(): string
    {
        return match ($this) {
            self::VICTINI => 'victini',
            self::SNIVY => 'snivy',
            self::SERVINE => 'servine',
            self::SERPERIOR => 'serperior',
            self::TEPIG => 'tepig',
            self::PIGNITE => 'pignite',
            self::EMBOAR => 'emboar',
            self::OSHAWOTT => 'oshawott',
            self::DEWOTT => 'dewott',
            self::SAMUROTT => 'samurott',
            self::PATRAT => 'patrat',
            self::WATCHOG => 'watchog',
            self::LILLIPUP => 'lillipup',
            self::HERDIER => 'herdier',
            self::STOUTLAND => 'stoutland',
            self::PURRLOIN => 'purrloin',
            self::LIEPARD => 'liepard',
            self::PANSAGE => 'pansage',
            self::SIMISAGE => 'simisage',
            self::PANSEAR => 'pansear',
            self::SIMISEAR => 'simisear',
            self::PANPOUR => 'panpour',
            self::SIMIPOUR => 'simipour',
            self::MUNNA => 'munna',
            self::MUSHARNA => 'musharna',
            self::PIDOVE => 'pidove',
            self::TRANQUILL => 'tranquill',
            self::UNFEZANT => 'unfezant',
            self::BLITZLE => 'blitzle',
            self::ZEBSTRIKA => 'zebstrika',
            self::ROGGENROLA => 'roggenrola',
            self::BOLDORE => 'boldore',
            self::GIGALITH => 'gigalith',
            self::WOOBAT => 'woobat',
            self::SWOOBAT => 'swoobat',
            self::DRILBUR => 'drilbur',
            self::EXCADRILL => 'excadrill',
            self::AUDINO => 'audino',
            self::TIMBURR => 'timburr',
            self::GURDURR => 'gurdurr',
            self::CONKELDURR => 'conkeldurr',
            self::TYMPOLE => 'tympole',
            self::PALPITOAD => 'palpitoad',
            self::SEISMITOAD => 'seismitoad',
            self::THROH => 'throh',
            self::SAWK => 'sawk',
            self::SEWADDLE => 'sewaddle',
            self::SWADLOON => 'swadloon',
            self::LEAVANNY => 'leavanny',
            self::VENIPEDE => 'venipede',
            self::WHIRLIPEDE => 'whirlipede',
            self::SCOLIPEDE => 'scolipede',
            self::COTTONEE => 'cottonee',
            self::WHIMSICOTT => 'whimsicott',
            self::PETILIL => 'petilil',
            self::LILLIGANT => 'lilligant',
            self::BASCULIN => 'basculin',
            self::SANDILE => 'sandile',
            self::KROKOROK => 'krokorok',
            self::KROOKODILE => 'krookodile',
            self::DARUMAKA => 'darumaka',
            self::DARMANITAN => 'darmanitan',
            self::MARACTUS => 'maractus',
            self::DWEBBLE => 'dwebble',
            self::CRUSTLE => 'crustle',
            self::SCRAGGY => 'scraggy',
            self::SCRAFTY => 'scrafty',
            self::SIGILYPH => 'sigilph',
            self::YAMASK => 'yamask',
            self::COFAGRIGUS => 'cofagrigus',
            self::TIRTOUGA => 'tirtouga',
            self::CARRACOSTA => 'carracosta',
            self::ARCHEN => 'archen',
            self::ARCHEOPS => 'archeops',
            self::TRUBBISH => 'trubbish',
            self::GARBODOR => 'garbodor',
            self::ZORUA => 'zorua',
            self::ZOROARK => 'zoroark',
            self::MINCCINO => 'minccino',
            self::CINCCINO => 'cinccino',
            self::GOTHITA => 'gothita',
            self::GOTHORITA => 'gothorita',
            self::GOTHITELLE => 'gothitelle',
            self::SOLOSIS => 'solosis',
            self::DUOSION => 'duosion',
            self::REUNICLUS => 'reuniclus',
            self::DUCKLETT => 'ducklett',
            self::SWANNA => 'swanna',
            self::VANILLITE => 'vanillite',
            self::VANILLISH => 'vanillish',
            self::VANILLUXE => 'vanilluxe',
            self::DEERLING => 'deerling',
            self::SAWSBUCK => 'sawsbuck',
            self::EMOLGA => 'emolga',
            self::KARRABLAST => 'karrablast',
            self::ESCAVALIER => 'escavalier',
            self::FOONGUS => 'foongus',
            self::AMOONGUSS => 'amoonguss',
            self::FRILLISH => 'frillish',
            self::JELLICENT => 'jellicent',
            self::ALOMOMOLA => 'alomomola',
            self::JOLTIK => 'joltik',
            self::GALVANTULA => 'galvantula',
            self::FERROSEED => 'ferroseed',
            self::FERROTHORN => 'ferrothorn',
            self::KLINK => 'klink',
            self::KLANG => 'klang',
            self::KLINKLANG => 'klinklang',
            self::TYNAMO => 'tynamo',
            self::EELEKTRIK => 'eelektrik',
            self::EELEKTROSS => 'eelektross',
            self::ELGYEM => 'elgyem',
            self::BEHEEYEM => 'beheeyem',
            self::LITWICK => 'litwick',
            self::LAMPENT => 'lampent',
            self::CHANDELURE => 'chandelure',
            self::AXEW => 'axew',
            self::FRAXURE => 'fraxure',
            self::HAXORUS => 'haxorus',
            self::CUBCHOO => 'cubchoo',
            self::BEARTIC => 'beartic',
            self::CRYOGONAL => 'cryogonal',
            self::SHELMET => 'shelmet',
            self::ACCELGOR => 'accelgor',
            self::STUNFISK => 'stunfisk',
            self::MIENFOO => 'mienfoo',
            self::MIENSHAO => 'mienshao',
            self::DRUDDIGON => 'druddigon',
            self::GOLETT => 'golett',
            self::GOLURK => 'golurk',
            self::PAWNIARD => 'pawniard',
            self::BISHARP => 'bisharp',
            self::BOUFFALANT => 'bouffalant',
            self::RUFFLET => 'rufflet',
            self::BRAVIARY => 'braviary',
            self::VULLABY => 'vullaby',
            self::MANDIBUZZ => 'mandibuzz',
            self::HEATMOR => 'heatmor',
            self::DURANT => 'durant',
            self::DEINO => 'deino',
            self::ZWEILOUS => 'zweilous',
            self::HYDREIGON => 'hydreigon',
            self::LARVESTA => 'larvesta',
            self::VOLCARONA => 'volcarona',
            self::COBALION => 'cobalion',
            self::TERRAKION => 'terrakion',
            self::VIRIZION => 'virizion',
            self::TORNADUS => 'tornadus',
            self::THUNDURUS => 'thundurus',
            self::RESHIRAM => 'reshiram',
            self::ZEKROM => 'zekrom',
            self::LANDORUS => 'landorus',
            self::KYUREM => 'kyurem',
            self::KELDEO => 'keldeo',
            self::MELOETTA => 'meloetta',
            self::GENESECT => 'genesect',
        };
    }

}
