<?php

declare(strict_types=1);

namespace App\Enums;

enum Gen7Pokemon: int
{
    case ROWLET = 722;
    case DARTRIX = 723;
    case DECIDUEYE = 724;
    case LITTEN = 725;
    case TORRACAT = 726;
    case INCINEROAR = 727;
    case POPPLIO = 728;
    case BRIONNE = 729;
    case PRIMARINA = 730;
    case PIKIPEK = 731;
    case TRUMBEAK = 732;
    case TOUCANNON = 733;
    case YUNGOOS = 734;
    case GUMSHOOS = 735;
    case GRUBBIN = 736;
    case CHARJABUG = 737;
    case VIKAVOLT = 738;
    case CRABRAWLER = 739;
    case CRABOMINABLE = 740;
    case ORICORIO = 741;
    case CUTIEFLY = 742;
    case RIBOMBEE = 743;
    case ROCKRUFF = 744;
    case LYCANROC = 745;
    case WISHIWASHI = 746;
    case MAREANIE = 747;
    case TOXAPEX = 748;
    case MUDBRAY = 749;
    case MUDSDALE = 750;
    case DEWPIDER = 751;
    case ARAQUANID = 752;
    case FOMANTIS = 753;
    case LURANTIS = 754;
    case MORELULL = 755;
    case SHIINOTIC = 756;
    case SALANDIT = 757;
    case SALAZZLE = 758;
    case STUFFUL = 759;
    case BEWEAR = 760;
    case BOUNSWEET = 761;
    case STEENEE = 762;
    case TSAREENA = 763;
    case COMFEY = 764;
    case ORANGURU = 765;
    case PASSIMIAN = 766;
    case WIMPOD = 767;
    case GOLISOPOD = 768;
    case SANDYGAST = 769;
    case PALOSSAND = 770;
    case PYUKUMUKU = 771;
    case TYPE_NULL = 772;
    case SILVALLY = 773;
    case MINIOR = 774;
    case KOMALA = 775;
    case TURTONATOR = 776;
    case TOGEDEMARU = 777;
    case MIMIKYU = 778;
    case BRUXISH = 779;
    case DRAMPA = 780;
    case DHELMISE = 781;
    case JANGMO_O = 782;
    case HAKAMO_O = 783;
    case KOMMO_O = 784;
    case TAPU_KOKO = 785;
    case TAPU_LELE = 786;
    case TAPU_BULU = 787;
    case TAPU_FINI = 788;
    case COSMOG = 789;
    case COSMOEM = 790;
    case SOLGALEO = 791;
    case LUNALA = 792;
    case NIHILEGO = 793;
    case BUZZWOLE = 794;
    case PHEROMOSA = 795;
    case XURKITREE = 796;
    case CELESTEELA = 797;
    case KARTANA = 798;
    case GUZZLORD = 799;
    case NECROZMA = 800;
    case MAGEARNA = 801;
    case MARSHADOW = 802;
    case POIPOLE = 803;
    case NAGANADEL = 804;
    case STAKATAKA = 805;
    case BLACEPHALON = 806;
    case ZERAORA = 807;
    case MELTAN = 808;
    case MELMETAL = 809;

    public function evolvesFrom(): self|null
    {
        return match ($this) {
            self::DARTRIX => self::ROWLET,
            self::DECIDUEYE => self::DARTRIX,
            self::TORRACAT => self::LITTEN,
            self::INCINEROAR => self::TORRACAT,
            self::BRIONNE => self::POPPLIO,
            self::PRIMARINA => self::BRIONNE,
            self::TRUMBEAK => self::PIKIPEK,
            self::TOUCANNON => self::TRUMBEAK,
            self::GUMSHOOS => self::YUNGOOS,
            self::CHARJABUG => self::GRUBBIN,
            self::VIKAVOLT => self::CHARJABUG,
            self::CRABOMINABLE => self::CRABRAWLER,
            self::RIBOMBEE => self::CUTIEFLY,
            self::LYCANROC => self::ROCKRUFF,
            self::TOXAPEX => self::MAREANIE,
            self::MUDSDALE => self::MUDBRAY,
            self::ARAQUANID => self::DEWPIDER,
            self::LURANTIS => self::FOMANTIS,
            self::SHIINOTIC => self::MORELULL,
            self::SALAZZLE => self::SALANDIT,
            self::BEWEAR => self::STUFFUL,
            self::STEENEE => self::BOUNSWEET,
            self::TSAREENA => self::STEENEE,
            self::GOLISOPOD => self::WIMPOD,
            self::PALOSSAND => self::SANDYGAST,
            self::SILVALLY => self::TYPE_NULL,
            self::HAKAMO_O => self::JANGMO_O,
            self::KOMMO_O => self::HAKAMO_O,
            self::COSMOEM => self::COSMOG,
            self::SOLGALEO => self::COSMOEM,
            self::LUNALA => self::SOLGALEO,
            self::NAGANADEL => self::POIPOLE,
            self::MELMETAL => self::MELTAN,
            default => null,
        };
    }

    public function name(): string
    {
        return match ($this) {
            self::ROWLET => 'Rowlet',
            self::DARTRIX => 'Dartrix',
            self::DECIDUEYE => 'Decidueye',
            self::LITTEN => 'Litten',
            self::TORRACAT => 'Torracat',
            self::INCINEROAR => 'Incineroar',
            self::POPPLIO => 'Popplio',
            self::BRIONNE => 'Brionne',
            self::PRIMARINA => 'Primarina',
            self::PIKIPEK => 'Pikipek',
            self::TRUMBEAK => 'Trumbeak',
            self::TOUCANNON => 'Toucannon',
            self::YUNGOOS => 'Yungoos',
            self::GUMSHOOS => 'Gumshoos',
            self::GRUBBIN => 'Grubbin',
            self::CHARJABUG => 'Charjabug',
            self::VIKAVOLT => 'Vikavolt',
            self::CRABRAWLER => 'Crabrawler',
            self::CRABOMINABLE => 'Crabominable',
            self::ORICORIO => 'Oricorio',
            self::CUTIEFLY => 'Cutiefly',
            self::RIBOMBEE => 'Ribombee',
            self::ROCKRUFF => 'Rockruff',
            self::LYCANROC => 'Lycanroc',
            self::WISHIWASHI => 'Wishiwashi',
            self::MAREANIE => 'Mareanie',
            self::TOXAPEX => 'Toxapex',
            self::MUDBRAY => 'Mudbray',
            self::MUDSDALE => 'Mudsdale',
            self::DEWPIDER => 'Dewpider',
            self::ARAQUANID => 'Araquanid',
            self::FOMANTIS => 'Fomantis',
            self::LURANTIS => 'Lurantis',
            self::MORELULL => 'Morelull',
            self::SHIINOTIC => 'Shiinotic',
            self::SALANDIT => 'Salandit',
            self::SALAZZLE => 'Salazzle',
            self::STUFFUL => 'Stufful',
            self::BEWEAR => 'bewear',
            self::BOUNSWEET => 'Bounsweet',
            self::STEENEE => 'Steenee',
            self::TSAREENA => 'Tsareena',
            self::COMFEY => 'Comfey',
            self::ORANGURU => 'Oranguru',
            self::PASSIMIAN => 'Passimian',
            self::WIMPOD => 'Wimpod',
            self::GOLISOPOD => 'Golisopod',
            self::SANDYGAST => 'Sandygast',
            self::PALOSSAND => 'Palossand',
            self::PYUKUMUKU => 'Pyukumuku',
            self::TYPE_NULL => 'Type: Null',
            self::SILVALLY => 'Silvally',
            self::MINIOR => 'Minior',
            self::KOMALA => 'Komala',
            self::TURTONATOR => 'Turtonator',
            self::TOGEDEMARU => 'Togedemaru',
            self::MIMIKYU => 'Mimikyu',
            self::BRUXISH => 'Bruxish',
            self::DRAMPA => 'Drampa',
            self::DHELMISE => 'Dhelmise',
            self::JANGMO_O => 'Jangmo-o',
            self::HAKAMO_O => 'Hakamo-o',
            self::KOMMO_O => 'Kommo-o',
            self::TAPU_KOKO => 'Tapu Koko',
            self::TAPU_LELE => 'Tapu Lele',
            self::TAPU_BULU => 'Tapu Bulu',
            self::TAPU_FINI => 'Tapu Fini',
            self::COSMOG => 'Cosmog',
            self::COSMOEM => 'Cosmoem',
            self::SOLGALEO => 'Solgaleo',
            self::LUNALA => 'Lunala',
            self::NIHILEGO => 'Nihilego',
            self::BUZZWOLE => 'Buzzwole',
            self::PHEROMOSA => 'Pheromosa',
            self::XURKITREE => 'Xurkitree',
            self::CELESTEELA => 'Celesteela',
            self::KARTANA => 'Kartana',
            self::GUZZLORD => 'Guzzlord',
            self::NECROZMA => 'Necrozma',
            self::MAGEARNA => 'Magearna',
            self::MARSHADOW => 'Marshadow',
            self::POIPOLE => 'Poipole',
            self::NAGANADEL => 'Naganadel',
            self::STAKATAKA => 'Stakataka',
            self::BLACEPHALON => 'Blacephalon',
            self::ZERAORA => 'Zeraora',
            self::MELTAN => 'Meltan',
            self::MELMETAL => 'Melmetal',
        };
    }

    public function slug(): string
    {
        return match ($this) {
            self::ROWLET => 'rowlet',
            self::DARTRIX => 'dartrix',
            self::DECIDUEYE => 'decidueye',
            self::LITTEN => 'litten',
            self::TORRACAT => 'torracat',
            self::INCINEROAR => 'incineroar',
            self::POPPLIO => 'popplio',
            self::BRIONNE => 'brionne',
            self::PRIMARINA => 'primarina',
            self::PIKIPEK => 'pikipek',
            self::TRUMBEAK => 'trumbeak',
            self::TOUCANNON => 'toucannon',
            self::YUNGOOS => 'yungoos',
            self::GUMSHOOS => 'gumshoos',
            self::GRUBBIN => 'grubbin',
            self::CHARJABUG => 'charjabug',
            self::VIKAVOLT => 'vikavolt',
            self::CRABRAWLER => 'crabrawler',
            self::CRABOMINABLE => 'crabominable',
            self::ORICORIO => 'oricorio',
            self::CUTIEFLY => 'cutiefly',
            self::RIBOMBEE => 'ribombee',
            self::ROCKRUFF => 'rockruff',
            self::LYCANROC => 'lycanroc',
            self::WISHIWASHI => 'wishiwashi',
            self::MAREANIE => 'mareanie',
            self::TOXAPEX => 'toxapex',
            self::MUDBRAY => 'mudbray',
            self::MUDSDALE => 'mudsdale',
            self::DEWPIDER => 'dewpider',
            self::ARAQUANID => 'araquanid',
            self::FOMANTIS => 'fomantis',
            self::LURANTIS => 'lurantis',
            self::MORELULL => 'morelull',
            self::SHIINOTIC => 'shiinotic',
            self::SALANDIT => 'salandit',
            self::SALAZZLE => 'salazzle',
            self::STUFFUL => 'stufful',
            self::BEWEAR => 'bewear',
            self::BOUNSWEET => 'bounsweet',
            self::STEENEE => 'steenee',
            self::TSAREENA => 'tsareena',
            self::COMFEY => 'comfey',
            self::ORANGURU => 'oranguru',
            self::PASSIMIAN => 'passimian',
            self::WIMPOD => 'wimpod',
            self::GOLISOPOD => 'golisopod',
            self::SANDYGAST => 'sandygast',
            self::PALOSSAND => 'palossand',
            self::PYUKUMUKU => 'pyukumuku',
            self::TYPE_NULL => 'type-null',
            self::SILVALLY => 'silvally',
            self::MINIOR => 'minior',
            self::KOMALA => 'komala',
            self::TURTONATOR => 'turtonator',
            self::TOGEDEMARU => 'togedemaru',
            self::MIMIKYU => 'mimikyu',
            self::BRUXISH => 'bruxish',
            self::DRAMPA => 'dramapion',
            self::DHELMISE => 'dhelmise',
            self::JANGMO_O => 'jangmo-o',
            self::HAKAMO_O => 'hakamo-o',
            self::KOMMO_O => 'kommo-o',
            self::TAPU_KOKO => 'tapu-koko',
            self::TAPU_LELE => 'tapu-lele',
            self::TAPU_BULU => 'tapu-bulu',
            self::TAPU_FINI => 'tapu-fini',
            self::COSMOG => 'cosmog',
            self::COSMOEM => 'cosmoem',
            self::SOLGALEO => 'solgaleo',
            self::LUNALA => 'lunala',
            self::NIHILEGO => 'nihilego',
            self::BUZZWOLE => 'buzzwole',
            self::PHEROMOSA => 'pheromosa',
            self::XURKITREE => 'xurkitree',
            self::CELESTEELA => 'celesteela',
            self::KARTANA => 'kartana',
            self::GUZZLORD => 'guzzlord',
            self::NECROZMA => 'necrozma',
            self::MAGEARNA => 'magearna',
            self::MARSHADOW => 'marshadow',
            self::POIPOLE => 'poipole',
            self::NAGANADEL => 'naganadel',
            self::STAKATAKA => 'stakataka',
            self::BLACEPHALON => 'blacephalon',
            self::ZERAORA => 'zeraora',
            self::MELTAN => 'meltan',
            self::MELMETAL => 'melmetal',
        };
    }
}
