<?php

declare(strict_types=1);

namespace App\Enums;

enum Gen8Pokemon: int
{
    case GROOKEY = 810;
    case THWACKEY = 811;
    case RILLABOOM = 812;
    case SCORBUNNY = 813;
    case RABOOT = 814;
    case CINDERACE = 815;
    case SOBBLE = 816;
    case DRIZZILE = 817;
    case INTELEON = 818;
    case SKWOVET = 819;
    case GREEDENT = 820;
    case ROOKIDEE = 821;
    case CORVISQUIRE = 822;
    case CORVIKNIGHT = 823;
    case BLIPBUG = 824;
    case DOTLER = 825;
    case ORBEETLE = 826;
    case NICKIT = 827;
    case THIEVUL = 828;
    case GOSSIFLEUR = 829;
    case ELDEGOSS = 830;
    case WOOLOO = 831;
    case DUBWOOL = 832;
    case CHEWTLE = 833;
    case DREDNAW = 834;
    case YAMPER = 835;
    case BOLTUND = 836;
    case ROLYCOLY = 837;
    case CARKOL = 838;
    case COALOSSAL = 839;
    case APPLIN = 840;
    case FLAPPLE = 841;
    case APPLETUN = 842;
    case SILICOBRA = 843;
    case SANDACONDA = 844;
    case CRAMORANT = 845;
    case ARROKUDA = 846;
    case BARRASKEWDA = 847;
    case TOXEL = 848;
    case TOXTRICITY = 849;
    case SIZZLIPEDE = 850;
    case CENTISKORCH = 851;
    case CLOBBOPUS = 852;
    case GRAPPLOCT = 853;
    case SINISTEA = 854;
    case POLTEAGEIST = 855;
    case HATENNA = 856;
    case HATTREM = 857;
    case HATTERENE = 858;
    case IMPIDIMP = 859;
    case MORGREM = 860;
    case GRIMMSNARL = 861;
    case OBSTAGOON = 862;
    case PERRSERKER = 863;
    case CURSOLA = 864;
    case SIRFETCHD = 865;
    case MR_RIME = 866;
    case RUNERIGUS = 867;
    case MILCERY = 868;
    case ALCREMIE = 869;
    case FALINKS = 870;
    case PINCURCHIN = 871;
    case SNOM = 872;
    case FROSMOTH = 873;
    case STONJOURNER = 874;
    case EISCUE = 875;
    case INDEEDEE = 876;
    case MORPEKO = 877;
    case CUFANT = 878;
    case COPPERAJAH = 879;
    case DRACOZOLT = 880;
    case ARCTOZOLT = 881;
    case DRACOVISH = 882;
    case ARCTOVISH = 883;
    case DURALUDON = 884;
    case DREEPY = 885;
    case DRAKLOAK = 886;
    case DRAGAPULT = 887;
    case ZACIAN = 888;
    case ZAMAZENTA = 889;
    case ETERNATUS = 890;
    case KUBFU = 891;
    case URSHIFU = 892;
    case ZARUDE = 893;
    case REGIELEKI = 894;
    case REGIDRAGO = 895;
    case GLASTRIER = 896;
    case SPECTRIER = 897;
    case CALYREX = 898;
    case WYRDEER = 899;
    case KLEAVOR = 900;
    case URSALUNA = 901;
    case BASCULEGION = 902;
    case SNEASLER = 903;
    case OVERQWIL = 904;
    case ENAMORUS = 905;

    public function evolvesFrom(): self|Gen1Pokemon|Gen2Pokemon|Gen3Pokemon|Gen5Pokemon|null
    {
        return match ($this) {
            self::THWACKEY => self::GROOKEY,
            self::RILLABOOM => self::THWACKEY,
            self::RABOOT => self::SCORBUNNY,
            self::CINDERACE => self::RABOOT,
            self::DRIZZILE => self::SOBBLE,
            self::INTELEON => self::DRIZZILE,
            self::GREEDENT => self::SKWOVET,
            self::CORVISQUIRE => self::ROOKIDEE,
            self::CORVIKNIGHT => self::CORVISQUIRE,
            self::DOTLER => self::BLIPBUG,
            self::ORBEETLE => self::DOTLER,
            self::THIEVUL => self::NICKIT,
            self::ELDEGOSS => self::GOSSIFLEUR,
            self::DUBWOOL => self::WOOLOO,
            self::DREDNAW => self::CHEWTLE,
            self::BOLTUND => self::YAMPER,
            self::CARKOL => self::ROLYCOLY,
            self::COALOSSAL => self::CARKOL,
            self::FLAPPLE => self::APPLIN,
            self::APPLETUN => self::APPLIN,
            self::SANDACONDA => self::SILICOBRA,
            self::BARRASKEWDA => self::ARROKUDA,
            self::TOXTRICITY => self::TOXEL,
            self::CENTISKORCH => self::SIZZLIPEDE,
            self::GRAPPLOCT => self::CLOBBOPUS,
            self::POLTEAGEIST => self::SINISTEA,
            self::HATTREM => self::HATENNA,
            self::HATTERENE => self::HATTREM,
            self::MORGREM => self::IMPIDIMP,
            self::GRIMMSNARL => self::MORGREM,
            self::OBSTAGOON => Gen3Pokemon::LINOONE,
            self::PERRSERKER => Gen1Pokemon::MEOWTH,
            self::SIRFETCHD => Gen1Pokemon::FARFETCHD,
            self::MR_RIME => Gen1Pokemon::MR_MIME,
            self::RUNERIGUS => Gen5Pokemon::YAMASK,
            self::ALCREMIE => self::MILCERY,
            self::FROSMOTH => self::SNOM,
            self::COPPERAJAH => self::CUFANT,
            self::DRAKLOAK => self::DREEPY,
            self::DRAGAPULT => self::DRAKLOAK,
            self::URSHIFU => self::KUBFU,
            self::WYRDEER => Gen2Pokemon::STANTLER,
            self::KLEAVOR => Gen1Pokemon::SCYTHER,
            self::URSALUNA => Gen2Pokemon::URSARING,
            self::BASCULEGION => Gen5Pokemon::BASCULIN,
            self::SNEASLER => Gen2Pokemon::SNEASEL,
            self::OVERQWIL => Gen2Pokemon::QWILFISH,
            default => $this,
        };
    }

    public function name(): string
    {
        return match ($this) {
            self::GROOKEY => 'Grookey',
            self::THWACKEY => 'Thwackey',
            self::RILLABOOM => 'Rillaboom',
            self::SCORBUNNY => 'Scorbunny',
            self::RABOOT => 'Raboot',
            self::CINDERACE => 'Cinderace',
            self::SOBBLE => 'Sobble',
            self::DRIZZILE => 'Drizzile',
            self::INTELEON => 'Inteleon',
            self::SKWOVET => 'Skwovet',
            self::GREEDENT => 'Greedent',
            self::ROOKIDEE => 'Rookidee',
            self::CORVISQUIRE => 'Corvisquire',
            self::CORVIKNIGHT => 'Corviknight',
            self::BLIPBUG => 'Blipbug',
            self::DOTLER => 'Dottler',
            self::ORBEETLE => 'Orbeetle',
            self::NICKIT => 'Nickit',
            self::THIEVUL => 'Thievul',
            self::GOSSIFLEUR => 'Gossifleur',
            self::ELDEGOSS => 'Eldegoss',
            self::WOOLOO => 'Wooloo',
            self::DUBWOOL => 'Dubwool',
            self::CHEWTLE => 'Chewtle',
            self::DREDNAW => 'Drednaw',
            self::YAMPER => 'Yamper',
            self::BOLTUND => 'Boltund',
            self::ROLYCOLY => 'Rolycoly',
            self::CARKOL => 'Carkol',
            self::COALOSSAL => 'Coalossal',
            self::APPLIN => 'Applin',
            self::FLAPPLE => 'Flapple',
            self::APPLETUN => 'Appletun',
            self::SILICOBRA => 'Silicobra',
            self::SANDACONDA => 'Sandaconda',
            self::CRAMORANT => 'Cramorant',
            self::ARROKUDA => 'Arrokuda',
            self::BARRASKEWDA => 'Barraskewda',
            self::TOXEL => 'Toxel',
            self::TOXTRICITY => 'Toxtricity',
            self::SIZZLIPEDE => 'Sizzlipede',
            self::CENTISKORCH => 'Centiskorch',
            self::CLOBBOPUS => 'Clobbopus',
            self::GRAPPLOCT => 'Grapploct',
            self::SINISTEA => 'Sinistea',
            self::POLTEAGEIST => 'Polteageist',
            self::HATENNA => 'Hatenna',
            self::HATTREM => 'Hattrem',
            self::HATTERENE => 'Hatterene',
            self::IMPIDIMP => 'Impidimp',
            self::MORGREM => 'Morgrem',
            self::GRIMMSNARL => 'Grimmsnarl',
            self::OBSTAGOON => 'Obstagoon',
            self::PERRSERKER => 'Perrserker',
            self::CURSOLA => 'Cursola',
            self::SIRFETCHD => 'Sirfetch\'d',
            self::MR_RIME => 'Mr. Rime',
            self::RUNERIGUS => 'Runerigus',
            self::MILCERY => 'Milcery',
            self::ALCREMIE => 'Alcremie',
            self::FALINKS => 'Falinks',
            self::PINCURCHIN => 'Pincurchin',
            self::SNOM => 'Snom',
            self::FROSMOTH => 'Frosmoth',
            self::STONJOURNER => 'Stonjourner',
            self::EISCUE => 'Eiscue',
            self::INDEEDEE => 'Indeedee',
            self::MORPEKO => 'Morpeko',
            self::CUFANT => 'Cufant',
            self::COPPERAJAH => 'Copperajah',
            self::DRACOZOLT => 'Dracozolt',
            self::ARCTOZOLT => 'Arctozolt',
            self::DRACOVISH => 'Dracovish',
            self::ARCTOVISH => 'Arctovish',
            self::DURALUDON => 'Duraludon',
            self::DREEPY => 'Dreepy',
            self::DRAKLOAK => 'Drakloak',
            self::DRAGAPULT => 'Dragapult',
            self::ZACIAN => 'Zacian',
            self::ZAMAZENTA => 'Zamazenta',
            self::ETERNATUS => 'Eternatus',
            self::KUBFU => 'Kubfu',
            self::URSHIFU => 'Urshifu',
            self::ZARUDE => 'Zarude',
            self::REGIELEKI => 'Regieleki',
            self::REGIDRAGO => 'Regidrago',
            self::GLASTRIER => 'Glastrier',
            self::SPECTRIER => 'Spectrier',
            self::CALYREX => 'Calyrex',
            self::WYRDEER => 'Wyrdeer',
            self::KLEAVOR => 'Kleavor',
            self::URSALUNA => 'Ursaluna',
            self::BASCULEGION => 'Basculegion',
            self::SNEASLER => 'Sneasler',
            self::OVERQWIL => 'Overqwil',
            self::ENAMORUS => 'Enamorus',
        };
    }

    public function slug(): string
    {
        return match ($this) {

            self::GROOKEY => 'grookey',
            self::THWACKEY => 'thwackey',
            self::RILLABOOM => 'rillaboom',
            self::SCORBUNNY => 'scorbunny',
            self::RABOOT => 'raboot',
            self::CINDERACE => 'cinderace',
            self::SOBBLE => 'sobble',
            self::DRIZZILE => 'drizzile',
            self::INTELEON => 'inteleon',
            self::SKWOVET => 'skwovet',
            self::GREEDENT => 'greedent',
            self::ROOKIDEE => 'rookidee',
            self::CORVISQUIRE => 'corvisquire',
            self::CORVIKNIGHT => 'corviknight',
            self::BLIPBUG => 'blipbug',
            self::DOTLER => 'dotler',
            self::ORBEETLE => 'orbeetle',
            self::NICKIT => 'nickit',
            self::THIEVUL => 'thievul',
            self::GOSSIFLEUR => 'gossifleur',
            self::ELDEGOSS => 'eldegoss',
            self::WOOLOO => 'wooloo',
            self::DUBWOOL => 'dubwool',
            self::CHEWTLE => 'chewtle',
            self::DREDNAW => 'drednaw',
            self::YAMPER => 'yamper',
            self::BOLTUND => 'boltund',
            self::ROLYCOLY => 'rolycoly',
            self::CARKOL => 'carkol',
            self::COALOSSAL => 'coalossal',
            self::APPLIN => 'applin',
            self::FLAPPLE => 'flapple',
            self::APPLETUN => 'appletun',
            self::SILICOBRA => 'silicobra',
            self::SANDACONDA => 'sandaconda',
            self::CRAMORANT => 'cramorant',
            self::ARROKUDA => 'arrokuda',
            self::BARRASKEWDA => 'barraskewda',
            self::TOXEL => 'toxel',
            self::TOXTRICITY => 'toxtricity',
            self::SIZZLIPEDE => 'sizzlipede',
            self::CENTISKORCH => 'centiskorch',
            self::CLOBBOPUS => 'clobbopus',
            self::GRAPPLOCT => 'grapploct',
            self::SINISTEA => 'sinistea',
            self::POLTEAGEIST => 'polteageist',
            self::HATENNA => 'hatenna',
            self::HATTREM => 'hattrem',
            self::HATTERENE => 'hatterene',
            self::IMPIDIMP => 'impidimp',
            self::MORGREM => 'morgrem',
            self::GRIMMSNARL => 'grimmsnarl',
            self::OBSTAGOON => 'obstagoon',
            self::PERRSERKER => 'perrserker',
            self::CURSOLA => 'cursola',
            self::SIRFETCHD => 'sirfetchd',
            self::MR_RIME => 'mr-rime',
            self::RUNERIGUS => 'runerigus',
            self::MILCERY => 'milcery',
            self::ALCREMIE => 'alcremie',
            self::FALINKS => 'falinks',
            self::PINCURCHIN => 'pincurchin',
            self::SNOM => 'snom',
            self::FROSMOTH => 'frosmoth',
            self::STONJOURNER => 'stonjourner',
            self::EISCUE => 'eiscue',
            self::INDEEDEE => 'indeedee',
            self::MORPEKO => 'morpeko',
            self::CUFANT => 'cufant',
            self::COPPERAJAH => 'copperajah',
            self::DRACOZOLT => 'dracozolt',
            self::ARCTOZOLT => 'arctozolt',
            self::DRACOVISH => 'dracovish',
            self::ARCTOVISH => 'arctovish',
            self::DURALUDON => 'duraludon',
            self::DREEPY => 'dreepy',
            self::DRAKLOAK => 'drakloak',
            self::DRAGAPULT => 'dragapult',
            self::ZACIAN => 'zacian',
            self::ZAMAZENTA => 'zamazenta',
            self::ETERNATUS => 'eternatus',
            self::KUBFU => 'kubfu',
            self::URSHIFU => 'urshifu',
            self::ZARUDE => 'zarude',
            self::REGIELEKI => 'regieleki',
            self::REGIDRAGO => 'regidrago',
            self::GLASTRIER => 'glastrier',
            self::SPECTRIER => 'spectrier',
            self::CALYREX => 'calyrex',
            self::WYRDEER => 'wyrdeer',
            self::KLEAVOR => 'kleavor',
            self::URSALUNA => 'ursaluna',
            self::BASCULEGION => 'basculegion',
            self::SNEASLER => 'sneasler',
            self::OVERQWIL => 'overqwil',
            self::ENAMORUS => 'enamorus',
        };
    }
}
